spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format-sql: true
        generate-statistics: true
logging:
  level:
    org:
      hibernate:
        stat: debug