server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/cart_db
    username: root
    password: r@th15h
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
